before:
  hooks:
    - go mod tidy
builds:
- skip: true
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^doc:'
    - '^test:'
    - '^chore:'
  groups:
    - title: 'New Features'
      regexp: "^.*feat:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix:+.*$"
      order: 1
